name: MARKETSHELPER CI

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-gateway:
    name: Gateway Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Gateway Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r gateway/requirements.txt

      - name: Run Gateway Unit Tests
        run: |
          python -m unittest discover -s gateway/tests -t gateway

  test-tenant-app:
    name: Tenant App Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Tenant App Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tenant-app/requirements.txt

      - name: Run Tenant App Unit Tests
        run: |
          python -m unittest discover -s tenant-app/tests -t tenant-app
